/*
 * SPDX-License-Identifier: BSD-3-Clause
 *
 * GENERATED FILE - do not edit.
 *
 * The built-in fallback manifest template, embedded from
 * templates/single-job.yaml.tmpl by contrib/embed-default-template.py.
 * Edit that template and re-run the script; edits made here are lost.
 */

#include "prte_config.h"

#include "plm_k8s_template.h"

const char prte_plm_k8s_default_template[] =
    "# plm/k8s default template - ONE Kubernetes object for the whole DVM.\n"
    "#\n"
    "# A Job with completions/parallelism equal to the number of daemons being\n"
    "# launched, so a single pod template covers every node. The two things\n"
    "# that shape everything below both come from \"single pod template\":\n"
    "#\n"
    "#   * The daemons' vpids cannot be in the env: block, because that block is\n"
    "#     shared by all the pods and every daemon needs a different one. So the\n"
    "#     env tag at global scope is exactly the common part - every PRTE_MCA /\n"
    "#     PMIX_MCA setting *except* ess_base_vpid - and each pod works out its\n"
    "#     own, below.\n"
    "#\n"
    "#   * Which pod lands on which node is the scheduler's call, not ours:\n"
    "#     Kubernetes has no way to bind replica i of a Job to node i.\n"
    "#\n"
    "# The second point is not a detail to wave away. PRRTE's allocation has\n"
    "# already decided that daemon 1 is on node A and daemon 2 is on node B, and\n"
    "# it maps application processes onto that. If the pods come up the other way\n"
    "# round, every daemon reports a hostname PRRTE assigned to a *different*\n"
    "# node, and PRRTE's node table ends up with two entries that have swapped\n"
    "# names - which does not merely mislocate processes, it corrupts the DVM.\n"
    "#\n"
    "# So the pod does not assume its placement: it reads the node it actually\n"
    "# landed on from the downward API and looks up the vpid PRRTE assigned to\n"
    "# *that* node in the node_vpids tag. Placement then does not have to be\n"
    "# controlled at all, only constrained - nodeAffinity to the allocated\n"
    "# nodes, podAntiAffinity to one daemon per node - and whatever the\n"
    "# scheduler decides, PRRTE's map still describes reality.\n"
    "#\n"
    "# (If you would rather pin explicitly, templates/list-of-jobs.yaml.tmpl\n"
    "# renders one nodeName-pinned Job per node instead. It is still one\n"
    "# document and one kubectl apply, but N objects.)\n"
    "#\n"
    "# Placeholders are documented in plm_k8s/plm_k8s_template.h. Keep the\n"
    "# prrte.kubepmix.dev/{managed-by,dvm} labels: shutdown cleanup deletes by\n"
    "# that selector and finds nothing without them.\n"
    "#\n"
    "# (The renderer does not parse YAML, so it substitutes tags inside these\n"
    "# comments too - which is why the prose above names them without writing\n"
    "# them out.)\n"
    "apiVersion: batch/v1\n"
    "kind: Job\n"
    "metadata:\n"
    "  name: {{name}}\n"
    "  labels:\n"
    "    prrte.kubepmix.dev/managed-by: plm-k8s\n"
    "    prrte.kubepmix.dev/dvm: \"{{name}}\"\n"
    "  annotations:\n"
    "    prrte.kubepmix.dev/nodes: \"{{nodes_csv}}\"\n"
    "spec:\n"
    "  completions: {{numnodes}}\n"
    "  parallelism: {{numnodes}}\n"
    "  backoffLimit: 0\n"
    "  ttlSecondsAfterFinished: 600\n"
    "  template:\n"
    "    metadata:\n"
    "      labels:\n"
    "        prrte.kubepmix.dev/managed-by: plm-k8s\n"
    "        prrte.kubepmix.dev/dvm: \"{{name}}\"\n"
    "    spec:\n"
    "      restartPolicy: Never\n"
    "      hostNetwork: true\n"
    "      dnsPolicy: ClusterFirstWithHostNet\n"
    "      affinity:\n"
    "        nodeAffinity:\n"
    "          requiredDuringSchedulingIgnoredDuringExecution:\n"
    "            nodeSelectorTerms:\n"
    "              - matchExpressions:\n"
    "                  - key: kubernetes.io/hostname\n"
    "                    operator: In\n"
    "                    values:\n"
    "                      {{#nodes}}\n"
    "                      - \"{{node}}\"\n"
    "                      {{/nodes}}\n"
    "        podAntiAffinity:\n"
    "          requiredDuringSchedulingIgnoredDuringExecution:\n"
    "            - topologyKey: kubernetes.io/hostname\n"
    "              labelSelector:\n"
    "                matchLabels:\n"
    "                  prrte.kubepmix.dev/dvm: \"{{name}}\"\n"
    "      containers:\n"
    "        - name: prted\n"
    "          image: job-runner:latest\n"
    "          imagePullPolicy: IfNotPresent\n"
    "          command: [\"/bin/sh\", \"-c\"]\n"
    "          args:\n"
    "            - |\n"
    "              # Take the vpid PRRTE assigned to the node we actually landed\n"
    "              # on. Failing loudly when it is not in the list matters: a\n"
    "              # daemon that guessed would corrupt the DVM's node table\n"
    "              # rather than fail, and that is far harder to diagnose.\n"
    "              IFS=,\n"
    "              for pair in $PRTE_K8S_NODE_VPIDS; do\n"
    "                case $pair in\n"
    "                  \"$PRTE_K8S_NODE\":*) PRTE_MCA_ess_base_vpid=${pair#*:} ;;\n"
    "                esac\n"
    "              done\n"
    "              unset IFS\n"
    "              if [ -z \"$PRTE_MCA_ess_base_vpid\" ]; then\n"
    "                echo \"plm/k8s: this pod landed on '$PRTE_K8S_NODE', which is not\" >&2\n"
    "                echo \"one of the allocated nodes ($PRTE_K8S_NODE_VPIDS) - refusing\" >&2\n"
    "                echo \"to start a daemon with an unknown identity.\" >&2\n"
    "                exit 1\n"
    "              fi\n"
    "              export PRTE_MCA_ess_base_vpid\n"
    "              exec prted\n"
    "          env:\n"
    "            - name: PRTE_K8S_NODE\n"
    "              valueFrom:\n"
    "                fieldRef:\n"
    "                  fieldPath: spec.nodeName\n"
    "            - name: PRTE_K8S_NODE_VPIDS\n"
    "              value: \"{{node_vpids}}\"\n"
    "            - name: PRTE_ALLOW_RUN_AS_ROOT\n"
    "              value: \"1\"\n"
    "            - name: PRTE_ALLOW_RUN_AS_ROOT_CONFIRM\n"
    "              value: \"1\"\n"
    "            {{env}}\n";
